{% set version = "0.13.0" %}

package:
  name: invoke
  version: {{ version }}

source:
  fn: invoke-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/invoke/invoke-{{ version }}.tar.gz
  sha256: 1a1992fac5292b97448d1c85dc0793e309c4c376acbc39ff067056d71fdc241d

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - invoke = invoke.main:program.run
    - inv = invoke.main:program.run

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - invoke
    - invoke.parser
    - invoke.vendor
    - invoke.vendor.fluidity
    - invoke.vendor.lexicon
    - invoke.vendor.yaml2    # [py2k]
    - invoke.vendor.yaml3    # [py3k]

  commands:
    - invoke --help
    - inv --help

about:
  home: http://docs.pyinvoke.org
  license: BSD-2-Clause
  summary: 'Pythonic task execution'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - nicoddemus
