{% set name = "invoke" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee6cbb101af1a859c7fe84f2a264c059020b0cb7fe3535f9424300ab568f6bd5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - invoke = invoke.main:program.run
    - inv = invoke.main:program.run
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

# tests disabled:
# E   Module not found "pytest_relaxed"
test:
  imports:
    - invoke
    - invoke.parser
    - invoke.vendor
    - invoke.vendor.fluidity
    - invoke.vendor.lexicon
  commands:
    - pip check
    - invoke --help
    - inv --help
  requires:
    - pip

about:
  home: https://docs.pyinvoke.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pythonic task execution'
  description: |
    Invoke is a Python (2.7 and 3.4+) library for managing shell-oriented subprocesses and organizing executable Python code into CLI-invokable tasks.
    It draws inspiration from various sources (make/rake, Fabric 1.x, etc) to arrive at a powerful & clean feature set.
  dev_url: https://github.com/pyinvoke/invoke
  doc_url: https://docs.pyinvoke.org

extra:
  recipe-maintainers:
    - ivoflipse
    - nicoddemus
