{% set version = "1.2.0" %}

package:
  name: invoke
  version: {{ version }}

source:
  fn: invoke-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/invoke/invoke-{{ version }}.tar.gz
  sha256: dc492f8f17a0746e92081aec3f86ae0b4750bf41607ea2ad87e5a7b5705121b7

build:
  number: 1000
  script: python -m pip install . --no-deps --ignore-installed
  entry_points:
    - invoke = invoke.main:program.run
    - inv = invoke.main:program.run

requirements:
  build:
    - pip
    - python    
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - invoke
    - invoke.parser
    - invoke.vendor
    - invoke.vendor.fluidity
    - invoke.vendor.lexicon
    - invoke.vendor.yaml2    # [py2k]
    - invoke.vendor.yaml3    # [py3k]

  commands:
    - invoke --help
    - inv --help

about:
  home: http://docs.pyinvoke.org
  license: BSD-2-Clause
  summary: 'Pythonic task execution'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - nicoddemus
