travis:
  secure:
    BINSTAR_TOKEN: EJbfp/C7GBKdwNorCocm2tdWuFAUIkFhRr8KbX4AbW8fJ6NRkU2Aif+iVcLlZBoIRUI0kiaqigZgG9nyKqiiTsTHu3KmVFKxwIFVE6zx6xdokzAm70z5TtvSQXNRQ/vdRmAKGmnCPoMfp8DE1C0mF+mkoVe2MMpEMFaQRF50lBYSkrZfMvWC1Pj+XgkmjSWoJwqBQlhTVERVUNB43ytpcaURymtG3Gy69zqccFzcfB7JE/uAT80/ub5sjUYRgH48WhDtwgbH1Ql55tX+Ixt8/t92IfgB01v5j06KBaO0dMiFBP9m5qQwCOGkQKnp0uzJwHi5dsL1htMPqxwmeSW11aGQIpZhzFWUiDM1/HEt/fdDneJhgj1xAKzElBoxI7YjK7jLIxfid2jJkiOD29jOuJxKZjwjlJ2DNyq3iqQqiU2/NN5tmTM+MaMNvj6VLBXqsOb0k6UFL/FtvCTxhb1KuoZ5GeXYhrrzAzii4Q2/9Z6tUEF677f347+oEtS92YVnwiI+BgSkvvuaGG/80Hjneli6vAxZL1/d7COPkFFe+isaOvgarj2gRz+7NZC2bUwUEnZPgISJvWU4f4GGFqdhXZ0mkx+ANAWdpatbdK7KY2WA+cRTNELrfr5zIWhB0moUhswPaCJXDBleXdQbBVDzjxBAffhblv5Cin+pcsJr1Oc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
