travis:
  secure:
    BINSTAR_TOKEN: Ot93ZetswDKpzuw68vzRKD0s7Zm5XIyi7386Ax4VUfefwofOWaXrUctZIRMmKeHMXWFWtoyNHxvhoh/Jo7BX4W1OAy82F1Y2EGPxmLUjYhGtrJVk9tqOd3D5KFFOXQ2OrpBlad34HoEnHLQlk/nJt8oWaERWqDCjS/wCWkkqAE9pXctr3GgqXDNLCJA3dY5NKFCJ4r3g5C7KOj7KsX4OtZg9dzskIxbYCUFtfHr6wu4tEBeJWgw/wq3qpeZ7xyYpJSbZzXHWM5xwWk2Z/k70qY1k+M9KOpA2cOinNHibAKOsIybv0XjuZSWcYWTVBLJZikvO2I+009TDXZ2JfVt2Ym+fmw89glmKzAJthu7N3RBgG8/bXLIWO/ahm+a+cQGr5l/dS9DWBMk5xz5uzp2GJz0RyVTrM/OobG902utjYqq2IUz/uIg0EPld6vYSWzQlDEur8CEvYnknxrtsQofVd8F7NjyGQ1iOOhTS5fX2zbwDXtax3q0B2VHBUJ3X6Np+PQ9UU9ZLq2Yz/2udT4JHoLy4DTbJBcNDy/qQYi0tIPgWIC3DGeIiXC8giIm05RSwlmQ+zSHuC4ggCaDDwJw21ZCFTlz1oLtcqKHue4aVLg0T0NoG1d3ZSc9t1CRZ6q0P36o3XvQ8MCUd+RDh2ZnMJtZu+uljItMtbY0cNizaOro=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
